### ISSUE TITLE
Wrong log massage

### ISSUE THREAD

**Issue by YinanWang16** [junrensia/SRL_process_output_public#1]
Hi Junren,  
This part is to get the "cid" and "wid", so you may want to change the error message from "{bsshvolume} folder acl updated" to something like "cid:{cid} and {bsshvolume} folder were found".
https://github.com/junrensia/SRL_process_output_public/blob/fab28365bb2e9ee83a3f1e2f0d160a58f2d6912d/docker/download_and_process.py#L196-L201

**Comment by junrensia** [comment]
Hi Yinan, thanks. You are right. I removed it entirely. Shouldn't have been there.
